In [1]:
import torch # 파이토치 모듈 불러오기

In [2]:
# 2차원 리스트로 실수형 텐서 만들기
ft = torch.FloatTensor([[1,2],
                       [3,4]])

In [3]:
ft

tensor([[1., 2.],
        [3., 4.]])

In [6]:
lt = torch.LongTensor([[1,2],
                        [3,4]])
lt

tensor([[1, 2],
        [3, 4]])

In [8]:
x = torch.FloatTensor(3,2) #3행 2열
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
import numpy as np

In [10]:
x = np.array([[1,2],
              [3,4]])
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [11]:
x

array([[1, 2],
       [3, 4]])

In [12]:
# 넘파이의 ndarray를 파이토치의 텐서로 변환
x = torch.from_numpy(x)
print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [14]:
#텐서를 ndarray로 변환
x = x.numpy()
print(x,type(x))

AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

In [15]:
ft

tensor([[1, 2],
        [3, 4]])

In [16]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [17]:
# 텐서의 크기를 구하는 방법
# 3x2x2 텐서 x를 선언
x = torch.FloatTensor([[[1,2],[3,4]],
                        [[5,6],[7,8]],
                       [[9,10],[11,12]]])
x              

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [22]:
print(x.size()) # 크기 메소드
print(x.shape) # 크기 속성

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [23]:
print(y.size()) # numpy에는 size()메서드가 없음
print(y.shape) # numpy의 shape은 튜플 형태임

NameError: name 'y' is not defined

In [29]:
print(x.dim())
print(len(x.size()))

3
3


In [45]:
a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[2,2],
                       [3,3]])
a

tensor([[1., 2.],
        [3., 4.]])

In [31]:
a + b

tensor([[3., 4.],
        [6., 7.]])

In [32]:
a - b

tensor([[-1.,  0.],
        [ 0.,  1.]])

In [33]:
a == b

tensor([[False,  True],
        [ True, False]])

In [34]:
a > b

tensor([[False, False],
        [False,  True]])

In [47]:
# 인플레이스(in-place) 연산
# 함수명 다음에 밑줄이 붙음
# 연산한 결과가 새로운 메모리에 할당되지 않고 원래 변수(텐서)에 저장됨
print(a.mul(b))

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [48]:
x = torch.from_numpy(np.arange(1,13).reshape(3,2,2))
x

tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])

In [49]:
x.view(12)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
x.view(3,-1)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [51]:
# view()함수의 결과는 텐서의 주소를 바꾸지 않음
x.view(3,4)
y = x.view(3,4)
x.data_ptr() == y.data_ptr()

True

In [52]:
# 따라서 y의 값을 바꾸면 x의 값도 바뀐다
y[0][0] = 100
y

tensor([[100,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]])

In [53]:
x

tensor([[[100,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]],

        [[  9,  10],
         [ 11,  12]]])

In [55]:
# 순차적으로 선언된(contoguous) 텐서가 아닐 경우 view함수는 오류를 발생시킴
# 오류를 방지하기 위해서는 다음과 같이 해야함
x.contiguous().view(-1)
x.reshape(-1)

tensor([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [57]:
x = torch.FloatTensor([[1,2],
                       [3,4]])
for i in range(2):
    for j in range(2):
        print(x[i][j].data_ptr())

4544615744
4544615748
4544615752
4544615756


In [58]:
x.stride()

(2, 1)

In [60]:
# squeeze 함수 
# 차원의 크기가 1인 차원을 제거함
x = torch.FloatTensor([[[1,2],[3,4]]])
x.size()

torch.Size([1, 2, 2])

In [61]:
x.squeeze()

tensor([[1., 2.],
        [3., 4.]])

In [62]:
x.squeeze().size()

torch.Size([2, 2])

In [63]:
# 원하는 차원을 지정해서 차원을 제거할 수 있음
print(x.squeeze(1).size())

torch.Size([1, 2, 2])


In [66]:
a = torch.FloatTensor([[[1],[2],[3]],[[4],[5],[6]]])
print(a)

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])


In [68]:
b = a.squeeze()
c = b.T
print(c)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [72]:
d = c.unsqueeze(0) # 맨 바깥에 차원을 하나 늘림
print(d)

tensor([[[1., 4.],
         [2., 5.],
         [3., 6.]]])


In [75]:
print(x[1:2,1:,:].size())
x

torch.Size([0, 1, 2])


tensor([[[1., 2.],
         [3., 4.]]])

In [77]:
x = torch.FloatTensor([[[1,2],
                        [3,4]],
                       [[5,6],
                        [7,8]],
                       [[9,10],
                        [11,12]]])
print(x.size())
                        

torch.Size([3, 2, 2])
