In [19]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [20]:
a.dtype

dtype('int64')

In [21]:
a = np.array([1,2,3.14,4])
a

array([1.  , 2.  , 3.14, 4.  ])

In [22]:
a.dtype # 요소 중에 실수가 섞여 잇으면 실수 배열이 생성됨

dtype('float64')

In [23]:
a.shape # 1행 4열

(4,)

- shpae 속성은 튜플로 표기되기 때문에 일차원 배열의 차원은 이렇게 콤마가 붙어서 나타남
- 1차원 배열은 행,열 개념이 없음 (그냥 4개의 원소)

In [24]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
b.shape # 2행 4열

(2, 4)

In [26]:
c = np.array([[1],[2],[3],[4]])
c

array([[1],
       [2],
       [3],
       [4]])

In [27]:
c.shape # 4행 1열

(4, 1)

### (4,1) 배열을 쉽게 만드는 방법
- (1,4) 배열을 만든 다음 전치(Transpose) 행렬 변환

In [30]:
d = np.array([[1,2,3,4,]])
d

array([[1, 2, 3, 4]])

In [31]:
d.T # 전치 행렬

array([[1],
       [2],
       [3],
       [4]])