In [2]:
import torch

In [2]:
ft = torch.FloatTensor([[1,2],
                        [3,4]])

In [4]:
ft # 2차원 리스트로 실수형 텐서 만들기

tensor([[1., 2.],
        [3., 4.]])

In [6]:
lt = torch.LongTensor([[1,2],
                        [3,4]])
lt # 정수형(long타입 -> 64bit) 텐서

tensor([[1, 2],
        [3, 4]])

In [8]:
bt = torch.ByteTensor([[1,2],
                        [3,4]])
bt # 부호없는 정수형 (8bit)

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [10]:
x = torch.FloatTensor(3,2) # 3행 2열 실수형 텐서를 생성
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

### 넘파이 호환

In [11]:
import numpy as np

x = np.array([[1,2],
              [3,4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [12]:
x

array([[1, 2],
       [3, 4]])

In [15]:
# 넘파이의 ndarray를 파이토치의 텐서로 변환
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [16]:
# 텐서를 ndarray로 변환
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


### 텐서의 타입 변환

In [20]:
ft

tensor([[1., 2.],
        [3., 4.]])

In [18]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [19]:
ft.float()

tensor([[1., 2.],
        [3., 4.]])

### 텐서의 크기 구하기

In [21]:
x = torch.FloatTensor([[[1,2],[3,4]],
                       [[5,6],[7,8]],
                       [[9,10],[11,12]]])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [23]:
y = np.arange(1,13).reshape(3,2,2) # 1부터 12까지 연속된 숫자 생성 / reshape으로 3,2,2 형태로 재배열
x = torch.from_numpy(y).float() # 넘파이 배열을 파이토치의 텐서로 변환
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [30]:
print(x.size()) # 크기 메서드 (함수 호출 -> 특정 차원 접근(차원을 인자로 받을 수 있음)
print(x.shape) #  크기 속성 (속성 접근)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [33]:
y.shape # 넘파이에는 size()가 없음

(3, 2, 2)

In [36]:
print(x.size(1))
print(x.shape[1])

2
2


In [38]:
# 차원의 개수
print(x.dim())
print(len(x.size()))

3
3


### 기본 연산

In [39]:
# 요소별 산술 연산
a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[2,2],
                       [3,3]])
a+b

tensor([[3., 4.],
        [6., 7.]])

In [40]:
# 논리연산 (==) 비교연산 (>,<) 전부 가능 -> True, False로 나옴

- 인플레이스 연산
  - 연산자 함수 옆에 _이 붙음
  - 결과에 대한 새로운 메모리를 할당하지 않고 텐서에 그대로 저장(값 업데이트)

In [45]:
a = torch.FloatTensor([[1,2],
                       [3,4]])
b = torch.FloatTensor([[2,2],
                       [3,3]])

In [46]:
a.mul(b)
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [47]:
a.mul_(b)
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])


### 차원 축소 연산 : 합과 평균
- 벡터(1차원 배열)의 합은 스칼라 값이므로 차원이 하나 줄어들게 됨

In [49]:
x = torch.FloatTensor([[1,2],
                       [3,4]])

In [51]:
print(x.sum()) # 합
print(x.mean()) # 평균

tensor(10.)
tensor(2.5000)


In [52]:
# 축을 지정핵서 차원을 줄일 수 있음
print(x.sum(dim=0))

tensor([4., 6.])


### 브로드캐스트 연산
- 크기가 다른 텐서들의 산술 연산을 가능하게 함
  - 텐서 + 스칼라
  - 텐서 + 벡터
  - 텐서 + 텐서

In [53]:
# 텐서 +  스칼라
x = torch.FloatTensor([[1,2],[3,4]])
y = 1
z = x + y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [54]:
# 텐서 + 벡터
x = torch.FloatTensor([[1,2],[4,8]])
y = torch.FloatTensor([3,5])
z = x + y
print(z)
print(z.size())

tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


### 텐서 형태 변환
- view 함수
  - 텐서의 요소 개수가 맞아야 함
  - -1이 들어간 차원의 크기는 다른 차원의 값들을 곱하고 남은 필요한 값이 자동으로 채워짐

In [61]:
x = torch.from_numpy(np.arange(1,13).reshape(3,2,2))

In [62]:
x.view(12)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [63]:
x.view(3,-1) # 요소 개수 : 12 / 0번째 차원 : 3 / -1은 미지수로 생각 -> 4가 채워짐

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [69]:
# 순차적으로 선언된 텐서가 아닐 경우 view()함수는 오류를 발생 
# 오류 방지를 위해 x.contiguous().view(-1) / x.reshpae(-1)울 해야함

x.contiguous().view(-1)
x.reshape(-1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Stride 함수

In [71]:
x = torch.FloatTensor([[1,2],[3,4]])
x.stride() # stride: 다음 요소로 접근하기 위해 건너뛰어야 할 요소의 수 (인덱스로 이해!!!)

(2, 1)

### squeeze 함수
- 크기가 1인 차원을 제거 함

In [1]:
a = torch.FloatTensor([[[1],[2],[3]],[[4],[5],[6]]])
a.size()

NameError: name 'torch' is not defined

In [75]:
x.squeeze()

tensor([[1., 2.],
        [3., 4.]])

In [80]:
print(x.squeeze(0).size())

torch.Size([2, 2])


In [81]:
print(x.squeeze(1).size())

torch.Size([1, 2, 2])


### unsqueeze 함수
- 크기가 1인 차원을 삽입 (삽입할 위치 지정)

In [86]:
x = torch.FloatTensor([[1,2],[3,4]])
x.size()

torch.Size([2, 2])

In [87]:
x.unsqueeze(1).size()

torch.Size([2, 1, 2])

In [88]:
x.unsqueeze(0).size()

torch.Size([1, 2, 2])

In [89]:
x.unsqueeze(2).size()

torch.Size([2, 2, 1])

In [90]:
x.unsqueeze(-1).size()

torch.Size([2, 2, 1])

In [3]:
import torch
a = torch.FloatTensor([[[1],[2],[3]],[[4],[5],[6]]])
print(a)

tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]]])


In [4]:
a.size()

torch.Size([2, 3, 1])

In [93]:
b = a.squeeze()

In [94]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [95]:
c = b.T

In [96]:
c

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [97]:
d = c.unsqueeze(0)

In [98]:
d

tensor([[[1., 4.],
         [2., 5.],
         [3., 6.]]])

### 텐서 자르기 & 붙이기

- 인덱싱과 슬라이싱
  - 넘파이와 동일함

In [100]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [101]:
print(x[0])

tensor([[1., 2.],
        [3., 4.]])


In [102]:
x.shape

torch.Size([3, 2, 2])

In [104]:
print(x[:,0])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [105]:
print(x[:,0,0])

tensor([1., 5., 9.])


In [106]:
print(x[1:2,1:,:].size())

torch.Size([1, 1, 2])


In [107]:
print(x[1:2,1:,:])

tensor([[[7., 8.]]])


### split 함수
- 텐서를 특정 차원에 대해서 원하는 크기로 잘라줌
- 원하는 크기로 나누고 마지막은 남은 것을 배분
- parameters
  - split_size : 나누는 조각의 크기
  - dim : 나누게 되는 차원

In [108]:
x = torch.FloatTensor(10,4)

In [109]:
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [110]:
splits = x.split(4,dim=0)

In [111]:
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


### chunk 함수
- 크기에 상관없이 원하는 개수로 나눔
- 최대한 같은 크기로 나누고 마지막에 나머지를 배분
- parameters
  - chunk: 나누는 조각의 개수
  - dim: 나누게 되는 차원

In [121]:
x = torch.FloatTensor(10,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [119]:
chunks = x.chunk(4,dim=0)

In [120]:
for c in chunks:
    print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([1, 4])


### Index_Select 함수
- 특정 차원에서 원하는 인덱스 위치의 값만 가져옴
- parameters
  - dim : 인덱스를 지정할 차원
  - index : 정수 텐서로 지정한 인덱스 목록

In [122]:
x = torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

In [123]:
indice = torch.LongTensor([2,1])

In [124]:
x.index_select(dim=0,index=indice)

tensor([[[ 9., 10.],
         [11., 12.]],

        [[ 5.,  6.],
         [ 7.,  8.]]])

### Concatenate 함수
- cat()
- 여러 텐서를 합쳐서 하나의 텐서로 만듬
- 합치는 차원을 dim으로 지정
- 합치는 차원 외 다른 차원들의 크기는 같아야 함
- parameters
  - tensors : 텐서목록
  - dim : int, optional

In [128]:
x = torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y = torch.FloatTensor([[10,11,12],[13,14,15],[16,17,18]])
print(x.size(), y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [127]:
torch.cat([x,y],dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

### Stack 함수
- cat() 함수와 비슷하게 텐서를 합치는 함수
- cat() 함수와 다르게 새로운 차원을 추가하여 합치는 텐서를 쌓는 방식으로 합침
- Numpy의 stack() 메서드와 같은 방식

In [131]:
x ,y

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 tensor([[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]))

In [130]:
torch.stack([x,y], dim=0)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [133]:
torch.cat([x.unsqueeze(0), y.unsqueeze(0)], dim=0) # stack()와 같음

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [139]:
torch.stack([x,y],dim=-1)

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])

### 유용한 함수들
### Expand 함수
- 차원의 크기가 1인 차원을 원하는 크기로 늘여줌
- [2,1,3] ---> [2,3,2]
- 확장되는 차원의 데이터는 원본데이터의 참조일 뿐 복사가 아님

In [140]:
x = torch.FloatTensor([[[1,2]],[[3,4]]])

In [141]:
x.size()

torch.Size([2, 1, 2])

In [142]:
y = x.expand(2,3,2)

In [143]:
print(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


In [144]:
y.size()

torch.Size([2, 3, 2])

In [147]:
y = torch.cat([x] * 3, dim=1) # cat()으로 구현

In [148]:
print(y)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])


### Random Permutation 함수
- randomperm()
- 인수로 주어진 숫자로, 0부터 해당 숫자 앞까지의 정수를 임의의 순서로 텐서를 만듬
- 순서를 섞어준다는 의미에서 Numpy의 shuffle()과 비슷함
- shuffle()은 주어진 데이터를 섞는 것이거, randomperm()은 1부터 해당 숫자까지 데이터를 생성해서 섞는 것이 다름

In [152]:
x = torch.randperm(10)
x # 딥러닝 학습에서 데이터를 무작위 순서로 넣어주기 위해 데이터의 인덱스를 섞어주는 역할로 사용

tensor([0, 9, 8, 3, 7, 6, 5, 1, 2, 4])

### Argument 함수
- argmax()
- X의 원소 중에서 함수 f(x)의 출력 값을 최대로 하는 입력 x를 반환함
- 즉, 함수 f(x)의 최대값이 나오는 텐서X의 인덱스를 반환함

In [162]:
x = torch.randperm(3**3).reshape(3,3,-1)
x

tensor([[[25, 13, 10],
         [26,  6, 15],
         [ 2, 20,  7]],

        [[16,  0, 21],
         [ 9,  1, 24],
         [12, 17,  8]],

        [[ 5, 19, 14],
         [22,  3, 18],
         [11,  4, 23]]])

In [165]:
x.argmax(dim=-1)

tensor([[0, 0, 1],
        [2, 2, 1],
        [1, 0, 2]])

### Top-k 함수
- topk()
- argmax() 함수는 가장 큰 값의 인덱스를 반환하는 것에 반해, topk() 함수는 가장 큰 값부터 k개의 값과 인덱스를 모두 반환함
- 따라서, k=1일때도 argmax()보다 차원이 하나 더 늘어남

In [184]:
values, indices = torch.topk(x, k=3, dim=-1)

In [185]:
values

tensor([[[25, 13, 10],
         [26, 15,  6],
         [20,  7,  2]],

        [[21, 16,  0],
         [24,  9,  1],
         [17, 12,  8]],

        [[19, 14,  5],
         [22, 18,  3],
         [23, 11,  4]]])

In [186]:
print(indices)

tensor([[[0, 1, 2],
         [0, 2, 1],
         [1, 2, 0]],

        [[2, 0, 1],
         [2, 0, 1],
         [1, 0, 2]],

        [[1, 2, 0],
         [0, 2, 1],
         [2, 0, 1]]])


### sort 함수
- sort()
- 텐서를 원하는 차원을 기준으로 정렬함

In [187]:
torch.sort(x, dim=-1)

torch.return_types.sort(
values=tensor([[[10, 13, 25],
         [ 6, 15, 26],
         [ 2,  7, 20]],

        [[ 0, 16, 21],
         [ 1,  9, 24],
         [ 8, 12, 17]],

        [[ 5, 14, 19],
         [ 3, 18, 22],
         [ 4, 11, 23]]]),
indices=tensor([[[2, 1, 0],
         [1, 2, 0],
         [0, 2, 1]],

        [[1, 0, 2],
         [1, 0, 2],
         [2, 0, 1]],

        [[0, 2, 1],
         [1, 2, 0],
         [1, 0, 2]]]))

In [189]:
target_dim = -1
torch.topk(x, k=x.size(target_dim), largest=False) # 기본값 : largest=True(큰 값부터 정렬)

torch.return_types.topk(
values=tensor([[[10, 13, 25],
         [ 6, 15, 26],
         [ 2,  7, 20]],

        [[ 0, 16, 21],
         [ 1,  9, 24],
         [ 8, 12, 17]],

        [[ 5, 14, 19],
         [ 3, 18, 22],
         [ 4, 11, 23]]]),
indices=tensor([[[2, 1, 0],
         [1, 2, 0],
         [0, 2, 1]],

        [[1, 0, 2],
         [1, 0, 2],
         [2, 0, 1]],

        [[0, 2, 1],
         [1, 2, 0],
         [1, 0, 2]]]))

In [191]:
x.size(-1)

3

### Masked Fill 함수
- masked_fill()
- 텐서 내의 원하는 부분만 특정 값으로 채움
- 원하는 위치는 마스크로 설정

In [196]:
x = torch.FloatTensor([i for i in range(3**2)]).reshape(3,-1)

In [197]:
x

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [198]:
mask = x > 4

In [199]:
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [201]:
x.masked_fill(mask, value=100)

tensor([[  0.,   1.,   2.],
        [  3.,   4., 100.],
        [100., 100., 100.]])

### Ones & zero 함수
- ones(), zeros()
- ones_like(), zero_like()
- Numpy의 함수와 같은 역할
- 차이점 : Numpy함수는 데이터의 크기를 하나의 리스트/튜플로 만들어서 넣어야 하지만, pytorch에서는 차원을 그래도 인수로 넣는다

In [204]:
import numpy as np
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [205]:
torch.ones(3,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [210]:
x = torch.FloatTensor([[[1,2]],[[3,4]]])

In [212]:
for i in range(2):
    for j in range(1):
        for k in range(2):
            print(x[i][j][k].data_ptr())

4813004096
4813004100
4813004104
4813004108


In [213]:
y = x.expand(2,3,2)

In [214]:
y

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [215]:
for i in range(2):
    for j in range(3):
        for k in range(2):
            print(y[i][j][k].data_ptr())

4813004096
4813004100
4813004096
4813004100
4813004096
4813004100
4813004104
4813004108
4813004104
4813004108
4813004104
4813004108


In [216]:
y.stride()

(2, 0, 1)

In [217]:
z = torch.cat([x]*3, dim=1)
z

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [218]:
z.stride()

(6, 2, 1)

In [ ]:
z