In [7]:
import torch
import torch.nn as nn

In [8]:
w = torch.FloatTensor([[1,2],
                       [3,4],
                       [5,6]])

In [9]:
b = torch.FloatTensor([2,2])

In [10]:
w.size()

torch.Size([3, 2])

In [16]:
x = torch.FloatTensor(4,3)

In [17]:
def linear(x,w,b):
    y = torch.matmul(x,w) + b
    return y

In [18]:
y = linear(x,w,b)
print(y.size())

torch.Size([4, 2])


In [4]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3,output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.w = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    def forward(self, x):
        y = torch.matmul(x, self.w) + self.b
        return y

In [19]:
linear = MyLinear(3,2)
y = linear(x)

In [20]:
y

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [26]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3,output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.w = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    def forward(self, x):
        y = torch.matmul(x, self.w) + self.b
        return y

In [27]:
linear = MyLinear(3,2)
y = linear(x)

In [28]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [33]:
linear = nn.Linear(3,2) # nn.Module에 미리 정의된 선형계층 사용
y = linear(x)
y

tensor([[0.0680, 0.1820],
        [0.0680, 0.1820],
        [0.0680, 0.1820],
        [0.0680, 0.1820]], grad_fn=<AddmmBackward0>)

In [34]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.4742,  0.4726,  0.3471],
        [ 0.0700, -0.4259, -0.5064]], requires_grad=True)
Parameter containing:
tensor([0.0680, 0.1820], requires_grad=True)


### Cuda 함수
- 딥러닝 연산은 연산량이 많기 때문에 GPU에서 이루어짐
- 앞선 코드들은 CPU에서 처리되도록 함
- 아래 코드들은 GPU에서 연산되도록 하는 코드들

In [35]:
x = torch.cuda.FloatTensor(2,2)
x

TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.