In [1]:
import torch
import torch.nn.functional as F

In [2]:
# 목표 텐서 생성
target = torch.FloatTensor([[.1,.2,.3],
                            [.4,.5,.6],
                            [.7,.8,.9]])

In [3]:
target

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])

In [8]:
# 랜덤 값을 가지는 텐서 생성
x = torch.rand_like(target) # target과 동일한 shpae을 가진 랜덤 텐서를 생성
x.requires_grad = True # 자동 편미분 활성화

In [10]:
print(x)

tensor([[0.4482, 0.0778, 0.9246],
        [0.0908, 0.4734, 0.2461],
        [0.0833, 0.2498, 0.4596]], requires_grad=True)


In [12]:
# 두 사이의 손실 값 계산
loss = F.mse_loss(x,target)
loss

tensor(0.1805, grad_fn=<MseLossBackward0>)

In [13]:
# 반복문을 통해 경사하강법을 적용하여 손실함수를 사용해 오차 값을 계속 줄여나감
threshold = 1e-5
learning_rate = 1
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    loss.backward()

    x = x - learning_rate * x.grad

    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(x,target)

    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 1.0921e-01
tensor([[0.3708, 0.1049, 0.7858],
        [0.1595, 0.4793, 0.3247],
        [0.2204, 0.3721, 0.5575]], requires_grad=True)
2-th Loss: 6.6063e-02
tensor([[0.3106, 0.1261, 0.6778],
        [0.2130, 0.4839, 0.3859],
        [0.3270, 0.4672, 0.6336]], requires_grad=True)
3-th Loss: 3.9964e-02
tensor([[0.2638, 0.1425, 0.5939],
        [0.2545, 0.4875, 0.4335],
        [0.4099, 0.5411, 0.6928]], requires_grad=True)
4-th Loss: 2.4176e-02
tensor([[0.2274, 0.1553, 0.5286],
        [0.2869, 0.4903, 0.4705],
        [0.4743, 0.5987, 0.7388]], requires_grad=True)
5-th Loss: 1.4625e-02
tensor([[0.1991, 0.1652, 0.4778],
        [0.3120, 0.4924, 0.4993],
        [0.5245, 0.6434, 0.7747]], requires_grad=True)
6-th Loss: 8.8472e-03
tensor([[0.1771, 0.1729, 0.4383],
        [0.3316, 0.4941, 0.5217],
        [0.5635, 0.6782, 0.8025]], requires_grad=True)
7-th Loss: 5.3520e-03
tensor([[0.1600, 0.1790, 0.4075],
        [0.3468, 0.4954, 0.5391],
        [0.5938, 0.7053, 0.8242]], requi

/var/folders/dc/3dqm8vys2qv2c52_q3sn76xr0000gn/T/ipykernel_76285/1204647954.py:17: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  print('%d-th Loss: %.4e' % (iter_cnt, loss))


In [15]:
# 오토그래드(자동미분기능)
x = torch.FloatTensor([[1,2],
                       [3,4]]).requires_grad_(True)

In [16]:
x1 = x + 2

In [17]:
x1

tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)

In [18]:
x2 = x - 2
x2

tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)

In [20]:
x3 = x1 * x2
x3

tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)

In [21]:
y = x3.sum()
y

tensor(14., grad_fn=<SumBackward0>)

In [22]:
y.backward() # y에 대해 편미분한 값을 .grad에 저장

In [24]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])
